### ISSUE TITLE
Query con 2 tablas

### ISSUE THREAD

**Issue by danielcanete** [prinick96/Ocrend-Framework#10]
Verás cuando ejecuto 
$this->db->query("SELECT * FROM `turbos`,`vehicles` WHERE turbos.ref LIKE '%753420%' ORDER BY turbos.ref DESC");
Me devuelve un error 500, tengo el debug activado pero no me devuelve una respuesta.
Si ese mismo codigo lo pegas directamente en el MySQL funciona perfectamente.

Espero que podais echarme una mano.

P.D: He intentado adjuntar una foto pero me da error el github.

**Comment by prinick96** [comment]
Si te da Error 500, significa que tu servidor no está mostrando los errores en pantalla, habilita que muestre los errores, ejecuta el script y pega aquí el error.

Te aseguro que el error no está en la query, si no en lo que probablemente haces con ella luego.

Saludos

**Comment by marcgdl** [comment]
Debe ser problema de tu consulta, yo utilizo consultas a múltiples tablas y todo funciona OK

**Comment by danielcanete** [comment]
Lo voy a revisar más a fondo, me quedo más tranquilo sabiendo que es un problema mio y no del framework.

Muchas gracias.
