### ISSUE TITLE
Problemas con loo nuevo de templates

### ISSUE THREAD

**Issue by virla01** [prinick96/Ocrend-Framework#12]
Hola Prinick, queria saber si con la nueva modalidad de los templates puede causar que algunas cosas como imagenes y css no cargen, me da 403 (Forbidden), y no es un tema de permisos ni que este mal puesta la ruta.
Es que vi que en el de twing agregaste 

# Insertar por defecto, en TODOS los templates un elemento
$this->template->addGlobal('session', $_SESSION);
$this->template->addGlobal('get', $_GET);
$this->template->addGlobal('post', $_POST);
$this->template->addGlobal('route', $this->route);

y en el plates lo dejastes vacio, por ahi hay que agregar algo, y no lo entendi

**Comment by virla01** [comment]
ya encontré cual era el problema. era en los permisos del .htaccess

**Comment by prinick96** [comment]
Justo eso te iba a decir que fijaras.

Saludos, cierro entonces.

**Comment by prinick96** [comment]
Luego subiré los videos y terminaré de escribir la documentación, es bastante x_x.
