### ISSUE TITLE
Obtener Ruta desde Conexión.php

### ISSUE THREAD

**Issue by marcgdl** [prinick96/Ocrend-Framework#13]
Hola Prinick

Estoy intentando agregar una bitácora de operaciones  (registro de transacciones en BD), es decir registrar todas las transacciones a la BD (insert,update,delete),

Agregue una función en Conexión que hace un insert, todo funciona bien, sin embargo no sé como sería la forma correcta de obtenerla desde este punto.

Duda adicional, se puede llamar un modelo desde otro modelo ? esto para suplir lo anterior y solo realizar un insert a decisión en alguna operación específica de X modelo, es decir;

Ejemplo;
Al actualizar un usuario, llamar desde el modelo Users al modelo Bitacora ($bitacora->log($rutaactual,$comentarios))

Gracias

**Comment by prinick96** [comment]
Claro que se puede llamar a un modelo desde otro modelo, son modelos todos. Heredan de Models, así que son "familia".

**Comment by marcgdl** [comment]
Excelente, gracias.
