### ISSUE TITLE
Permitir consulta API desde ubicación externa

### ISSUE THREAD

**Issue by marcgdl** [prinick96/Ocrend-Framework#14]
Hola Prinick

Tengo la necesidad de realizar algunas consultas a la API desde una ubicación externa, he realizado, una prueba rápida y obtengo la respuesta "Posting from another server not allowed".

Mi duda es si existe una manera de permitir estas consultas externas pero solo a las que pueda especificar, es decir como hacer esto teniendo control y no dejar abierta en su totalidad la api intentando este objetivo.

Saludos y gracias de antemano.

**Comment by prinick96** [comment]
Las peticiones externas se manejan en **./api/map.php**, cualquier otra petición externa será bloqueada. Encima, hay que habilitarlo desde el Firewall.
```php
'PROTECTION_DOS' => IS_API ? true : true,
```
Reemplazar por 
```php
'PROTECTION_DOS' => IS_API ? false : true,
```

**Comment by marcgdl** [comment]
Ya he realizado el cambio que sugieres, sin embargo me sigue arrojando el mismo mensaje, obviamente si cambio "'PROTECTION_REQUEST_SERVER' => false", me permite realizar las consultas.

Sin embargo realizando este cambio permite acceder a los metodos de map.php así como a post.php
: (

**Comment by prinick96** [comment]
Si mantienes PROTECTION_REQUEST_SERVER estás permitiendo que accedan mediante http POST y GET, y es ello lo que quieres entonces?

**Comment by marcgdl** [comment]
Lo que quiero es acceder a la api por POST desde una ubicación externar al servidor, mi intención sería mantener la seguridad de firewall y de alguna manera permitir el acceso externo a métodos que yo especifique.

Se me ocurre, que al detectar el acceso desde otro servidor llame algo así de post_ext.php, para de esta manera solo permitir a externos los métodos que ahí especifique y a todo lo que este en post.php
