### ISSUE TITLE
Sección para aplicaciones de terceros

### ISSUE THREAD

**Issue by virla01** [prinick96/Ocrend-Framework#15]
Estaría bueno que pudieras tener alguna sección en la web donde poder subir aplicaciones realizadas para ocrend, para que los usuarios puedan utilizarlas, tambien colaborar o corregir.
Yo tengo algunas que podría subir

**Comment by prinick96** [comment]
Tenía la idea de hacer un foro, pero no cuento con mucho tiempo para mantenerlo. Súbelas a github, dejas el repo por aquí y las adjunto en la documentación.

**Comment by virla01** [comment]
ok, apenas pueda tener algo preparado para subir lo hago. ahora estoy terminando un proyecto.
