### ISSUE TITLE
Integrar SDK AWS

### ISSUE THREAD

**Issue by marcgdl** [prinick96/Ocrend-Framework#18]
Hola

Estoy intentando integrar el SDK de AWS, específicamente para cargar los referente a IAM y S3.

El SDK tiene su propia autocarga de clases;

`require 'aws/aws-autoloader.php';

function crearBucket($usuario){
    $s3 = new Aws\S3\S3Client([
        'version'     => 'latest',
        'region'      => 'us-west-2',`

Desde un documento "php" puedo realizar las pruebas y todo lo que necesito de manera correcta, mi duda es como crear dentro del framework alguna clase que implemente las funciones que necesito para poder llamarlas dentro del framework, estoy perdido en como mezclar las clases o llamarlas.

**Comment by prinick96** [comment]
Usa composer
```
composer require aws/aws-sdk-php
```

Se instalará todo en vendor, y ya podrás usar todo en cualquier sitio, no tienes que configurar nada.

**Comment by marcgdl** [comment]
Hola, he integrado el SDK con composer como me recomendaste, pero es necesario que agregue el "use Aws\S3\S3Client;" al inicio de donde quiero utilizarlo (api, models, etc.) que debería revisar para que funcione como las demas librerías ?
