### ISSUE TITLE
Soporte para MSSQL

### ISSUE THREAD

**Issue by marcgdl** [prinick96/Ocrend-Framework#2]
Saludos

Un gran trabajo el framework, en la documentación se muestra soporte para MS SQL, sin embargo en el archivo de configuración "core/config.php" no se muestra la opción para este motor, se tendría que realizar la conexión por ODBC o falta su implementación en el framework ?

**Comment by prinick96** [comment]
Podrías intentar conectar con ODBC, lo he retirado porque no se mostraba muy estable directamente el driver de PDO que se utiliza para realizar la conexión con MS SQL pero queda pendiente-

**Comment by marcgdl** [comment]
Gracias por tu respuesta, he intentado con ODBC, pero he revisado la conexión usando odbc, pero me parece que al llamar el constructor la cadena de conexión con los parámetros es igual a 'odbc:NOMBREBD', esto es lo correcto ? o esta incompleta la conexión con este método.

**Comment by prinick96** [comment]
Puedes manipularla a tu manera, está incompleta porque no es muy común, si la puedes acomodar y subirla a algún sitio con gusto la pondría para la próxima versión.

Pero algo básico sería:

``` php
parent::__construct('odbc:'.$DATABASE, DATABASE['user'],DATABASE['pass']);
```

Donde **$DATABASE** sea **MSSQLServer**

**Comment by marcgdl** [comment]
Excelente, trataré de implementarla y una vez probado te hago llegar los comentarios respectivos, gracias.

P.D. Es un excelente trabajo, gracias.
