### ISSUE TITLE
Probando el firewall encontre un error

### ISSUE THREAD

**Issue by virla01** [prinick96/Ocrend-Framework#21]
http://localhost/Ocrend-Framework/?v=<script src="algo.js"><script>
me da el siquiente error
`<table class="xdebug-error xe-fatal-error" dir="ltr" border="1" cellspacing="0" cellpadding="1">
<tbody><tr><th align="left" bgcolor="#f57900" colspan="5"><span style="background-color: #cc0000; color: #fce94f; font-size: x-large;">( ! )</span> Fatal error: Class 'Twig_Extension' not found in D:\wamp64\www\Ocrend-Framework\core\models\Func.php on line <i>8</i></th></tr>
<tr><th align="left" bgcolor="#e9b96e" colspan="5">Call Stack</th></tr>
<tr><th align="center" bgcolor="#eeeeec">#</th><th align="left" bgcolor="#eeeeec">Time</th><th align="left" bgcolor="#eeeeec">Memory</th><th align="left" bgcolor="#eeeeec">Function</th><th align="left" bgcolor="#eeeeec">Location</th></tr>
<tr><td bgcolor="#eeeeec" align="center">1</td><td bgcolor="#eeeeec" align="center">0.0005</td><td bgcolor="#eeeeec" align="right">366776</td><td bgcolor="#eeeeec">{main}(  )</td><td title="D:\wamp64\www\Ocrend-Framework\index.php" bgcolor="#eeeeec">...\index.php<b>:</b>0</td></tr>
<tr><td bgcolor="#eeeeec" align="center">2</td><td bgcolor="#eeeeec" align="center">0.0006</td><td bgcolor="#eeeeec" align="right">372864</td><td bgcolor="#eeeeec">require( <font color="#00bb00">'D:\wamp64\www\Ocrend-Framework\core\app_core.php'</font> )</td><td title="D:\wamp64\www\Ocrend-Framework\index.php" bgcolor="#eeeeec">...\index.php<b>:</b>18</td></tr>
<tr><td bgcolor="#eeeeec" align="center">3</td><td bgcolor="#eeeeec" align="center">0.0013</td><td bgcolor="#eeeeec" align="right">384520</td><td bgcolor="#eeeeec">require( <font color="#00bb00">'D:\wamp64\www\Ocrend-Framework\core\kernel\Ocrend.php'</font> )</td><td title="D:\wamp64\www\Ocrend-Framework\core\app_core.php" bgcolor="#eeeeec">...\app_core.php<b>:</b>29</td></tr>
<tr><td bgcolor="#eeeeec" align="center">4</td><td bgcolor="#eeeeec" align="center">0.0027</td><td bgcolor="#eeeeec" align="right">632464</td><td bgcolor="#eeeeec">Firewall-&gt;__construct(  )</td><td title="D:\wamp64\www\Ocrend-Framework\core\kernel\Ocrend.php" bgcolor="#eeeeec">...\Ocrend.php<b>:</b>39</td></tr>
<tr><td bgcolor="#eeeeec" align="center">5</td><td bgcolor="#eeeeec" align="center">0.0110</td><td bgcolor="#eeeeec" align="right">647096</td><td bgcolor="#eeeeec"><a href="http://www.php.net/function.spl-autoload-call" target="_new">spl_autoload_call</a>
(  )</td><td title="D:\wamp64\www\Ocrend-Framework\core\kernel\Firewall.php" bgcolor="#eeeeec">...\Firewall.php<b>:</b>522</td></tr>
<tr><td bgcolor="#eeeeec" align="center">6</td><td bgcolor="#eeeeec" align="center">0.0111</td><td bgcolor="#eeeeec" align="right">647176</td><td bgcolor="#eeeeec">__models_autoload(  )</td><td title="D:\wamp64\www\Ocrend-Framework\core\kernel\Firewall.php" bgcolor="#eeeeec">...\Firewall.php<b>:</b>522</td></tr>
<tr><td bgcolor="#eeeeec" align="center">7</td><td bgcolor="#eeeeec" align="center">0.0119</td><td bgcolor="#eeeeec" align="right">671208</td><td bgcolor="#eeeeec">require_once( <font color="#00bb00">'D:\wamp64\www\Ocrend-Framework\core\models\Func.php'</font> )</td><td title="D:\wamp64\www\Ocrend-Framework\core\kernel\Ocrend.php" bgcolor="#eeeeec">...\Ocrend.php<b>:</b>32</td></tr>
</tbody></table>`

**Comment by prinick96** [comment]
[Fix](https://github.com/prinick96/Ocrend-Framework/commit/2cd30e1081eaf3ce292b3cc1077735928b1088ea)

Muchas gracias por informar!
