### ISSUE TITLE
Como hago para realizar esta consulta

### ISSUE THREAD

**Issue by virla01** [prinick96/Ocrend-Framework#22]
Esta es una que encontré de ejemplo:
`SELECT year, country, product, SUM(profit) AS profit FROM sales GROUP BY year ASC, country ASC, product ASC;`

yo hice esta: 
`$this->db->select('countid,countryName,navegador,plataforma, SUM(useragent) AS visitas','visitas','GROUP BY countid ASC,countryName ASC,navegador ASC,plataforma ASC');`

pero me sale error: 
`Error en la query: SELECT countid,countryName,navegador,plataforma, SUM(useragent) AS visitas FROM visitas WHERE GROUP BY countid ASC,countryName ASC,navegador ASC,plataforma ASC ;`
por lo que veo es por el WHERE

**Comment by prinick96** [comment]
```php
$this->db->query("SELECT year, country, product, SUM(profit) AS profit FROM sales GROUP BY year ASC, country ASC, product ASC;");
```

**Comment by virla01** [comment]
ok lo hice, pero el return me retorna
`PDOStatement Object ( [queryString] => SELECT countid,countryName,navegador,plataforma, SUM(useragent) AS useragent FROM visitas GROUP BY countid ASC, countryName ASC, navegador ASC,plataforma ASC; )`
al hacer un print_r

**Comment by prinick96** [comment]
```php
$this->db->fetch_array()
```

[Documentación Oficial](http://framework.ocrend.com/modelos/)
