### ISSUE TITLE
error al querer ingresar

### ISSUE THREAD

**Issue by virla01** [prinick96/Ocrend-Framework#24]
Ayer subi todo el framework a un servidor para probar algunas cosas y me encuentro con un error y estuve buscando ayer y casi todo el dia hoy y no logro encontrar el porque, por ahí sepas de que se trata.

Esta página no funciona
te redireccionó demasiadas veces.
Intenta borrar tus cookies.
ERR_TOO_MANY_REDIRECTS

Aprovecho esta consulta para hacerte otra más
Estoy adaptando un sistema de estadisticas(stats) y me crea unas imagenes en archivos php, el cual los estoy guardando en la misma carpeta donde esta la plantilla, como puedo hacer para q este archivo pueda conectarce a la base de datos?
gracias!

**Comment by marcgdl** [comment]
Hola, yo me tope con algo similar y creo que debes verificar el .htaccess, adicional a eso puede ser problemas en tu mecanismo de login si es que modificaste algo en el framework, saludos.

**Comment by prinick96** [comment]
Revisa las redirecciones, si modificaste el controlador principal homeController para que solo se accediera logeado, o cosas similares.

Estás cayendo en un re direccionamiento infinito.

**Comment by virla01** [comment]
Si vi que algo de los true o false del controlador tenia algo que ver, pero de cualquier manera, nunca puedo entrar al login, si a la administracion sin logearme.
esto es lo que me da el navedador
`http://www.aspectox-ocrend.esy.es/administrador/login/                        [HTTP/1.1 302 Found 218ms]`
`Encabezado de respuesta
Cache-Controlno-store, no-cache, must-revalidateConnectionKeep-AliveContent-EncodinggzipContent-Typetext/html; charset=UTF-8DateWed, 12 Apr 2017 18:04:59 GMTExpiresThu, 19 Nov 1981 08:52:00 GMTKeep-Alivetimeout=2, max=80Locationhttp://www.aspectox-ocrend.esy.es/administrador/login/Pragmano-cacheServerApacheTransfer-EncodingchunkedVaryAccept-EncodingX-Powered-ByPHP/7.0.6`
`Accepttext/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8Accept-Encodinggzip, deflateAccept-Languagees-AR,es;q=0.8,en-US;q=0.5,en;q=0.3Connectionkeep-aliveCookiePHPSESSID=d106522b4e3a63a168b859bfbd617739Hostwww.aspectox-ocrend.esy.esUpgrade-Insecure-Requests1User-AgentMozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0`

**Comment by prinick96** [comment]
Sube a gist tu Controller.php y comparte el link

**Comment by virla01** [comment]
ok, ahora lo hago, pero el problema esta me parece con el htaccess, porque en el home, que solo tenia esa pagina nada mas agregue una de prueba y no hace nada me vuelve al home.
voy a acualizarlo y comparto el link

**Comment by virla01** [comment]
Comparto todo por las dudas, total ya esta cargado y actualizado.
https://github.com/virla01/Ocrend-Framework-by-AspectoX

pero la modificacion mas grande no es en el controller, sino en  el ruter

**Comment by virla01** [comment]
alguna idea?

**Comment by prinick96** [comment]
Qué modificación pretendías hacer en el Router?

**Comment by virla01** [comment]
Tengo separado por aplicación, digamos q cada controlador esta en su carpeta.
Cree un manejador q identifica q aplicación es y se dirige, ejemplo a: app/usuarios/controller/usersController.php.
La modificación q hice es para eso, el identificador q cree es $apli que identifica la aplicación si lo q entra es / ingresa al home sino busca la aplicaciion

**Comment by prinick96** [comment]
Solo te queda hacer pruebas unitarias, revisa la lógica de loginController.php, quita los parámetros que le pasas al constructor, si funciona entonces chequea la lógica en Controllers.php para cuando tienes esos parámetros.

**Comment by virla01** [comment]
Prinick lo que no entiendo es: porque en modo local funciona todo bien y cuando lo subo al servidor no funciona?, no sera quizas el htaccess? la logica me dice que es eso, ya que eso no lo toque

**Comment by virla01** [comment]
ahora deje el router como viene de fabrica y cambie en el inicio esto:
`
# Detección del controlador actual
$Controller = $router->getController();
$apli = str_replace('Controller', '', $Controller);
$aplicacion = "";

//------------------------------------------------

# Identificación del controlador en el sistema
if(is_readable('app/aplicaciones/' . $apli . '/controllers/' . $Controller . '.php')) {
  $aplicacion = 'app/aplicaciones/' . $apli . '/controllers/' . $Controller . '.php';
}

if(!$aplicacion){
  if(!is_readable('app/aplicaciones/controllers/' . $Controller . '.php')) {
    $Controller = 'errorController';
  }
  require('app/aplicaciones/controllers/' . $Controller . '.php');
}else{
  require($aplicacion);
}`
al querer entrar a un controlador ejemplo, me vuelve al home.
ejemplo esta en:
app/aplicaciones/ejemplo/controllers/ejemploController.php

**Comment by virla01** [comment]
teniendo el código anterior, agregue una linea para ver que resultado me daba.
`# Detección del controlador actual
$Controller = $router->getController();
$apli = str_replace('Controller', '', $Controller);
$aplicacion = "";

//------------------------------------------------

echo 'Aplicación: ' . $apli . ' | Controlador: ' . $Controller;
die();`

y ponga lo que ponga en la ruta siempre me sale home | homeController.
he probado de todo y no se me ocurre mas nada, lo raro de todo esto y creo que ya lo dije, es que localmente todo funciona bien pero en el servidor es el problema, será que tengo que cambiar alguna cosa en la configuración del mismo?

**Comment by virla01** [comment]
alguien que me pueda dar una mano?

**Comment by virla01** [comment]
viendo que nadie respondía, seguí mirando y la verdad ya no se me ocurría nada, así que decidí volver a los tan queridos vídeos desde el comienzo, y ahí fue donde encontré el problema,
olvide que el __ROOT__ en el un servidor tenia que estar '/' y yo ponía la el nombre del dominio junto a las dos /. ahi se soluciono todo.
Igualmente muchas gracias.
