### ISSUE TITLE
Recomendación Hosting

### ISSUE THREAD

**Issue by marcgdl** [prinick96/Ocrend-Framework#25]
Saludos, no tiene mucho que ver pero pueden recomendarme un hosting que utilice php 7.1 para utilizar con el framework, gracias. @prinick96

**Comment by prinick96** [comment]
Namecheap, 1&1, digital ocean o cualquier vps

**Comment by virla01** [comment]
hostinger.es este es pago y tambien tenes la opción gratuita, que es la que estoy utilizando yo ahora
