### ISSUE TITLE
al pasar una url con datos, me tira un error el logs

### ISSUE THREAD

**Issue by virla01** [prinick96/Ocrend-Framework#26]
mando esto una vez desde el footer
`img = new Image(1,1);
img.src = "counter/?sw=" + screen.width + "&sc=" + screen.colorDepth + "&page=" + location.href + "&referer=" + web_referrer;`
a través de javascript y me sale error en el logs.
URL protect
hay alguna manera de que el firewall no tome esto como error. o alguna manera de hacer lo mismo pero que no marque el error?
gracias

**Comment by prinick96** [comment]
Pon en false la constante de configuración **PROTECTION_URL** en **./core/kernel/Firewall.php**

**Comment by virla01** [comment]
lo puse en false como me dijiste y ahora sale error XSS attack
