### ISSUE TITLE
update compose

### ISSUE THREAD

**Issue by jescobedoD** [prinick96/Ocrend-Framework#27]
Hola  estoy tratando de instalar vía composer la libreria log4php , ya tengo definida el require en el archivo composer.json pero al hacer update  me arroja un error en las dependencias.

 
![captura](https://cloud.githubusercontent.com/assets/6155599/25955883/c2265c4c-3640-11e7-95d9-2765f459b494.PNG)

saludos

**Comment by virla01** [comment]
se me hace que esto tiene que ver con la librería oauth2-google, tendrias que buscarlo en internet seguro que algo hay.

**Comment by prinick96** [comment]
``` 
composer require league/oauth2-google
```
