### ISSUE TITLE
Experiencia 1and1

### ISSUE THREAD

**Issue by marcgdl** [prinick96/Ocrend-Framework#28]
Hola a todos, quisiera preguntarles si alguien utiliza o a utilizado 1and1 con el framework, no consigo hacer funcionar la aplicación y tiene que ver con el .htaccess.

Alguien que pueda orientarme al respecto o que haya tenido una experiencia similar ?

**Comment by marcgdl** [comment]
Saludos, les comparto que ya pude solucionarlo de la siguiente manera:

`RewriteEngine On
RewriteBase /
Options -MultiViews
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ index.php [QSA,L]`

Agregue un par de líneas y con eso pude solucionarlo, espero le sirva a alguien más.

**Comment by lekir** [comment]
A mi no me va la API REST, me abre siempre la alerta de error. He puesto tus líneas en el .htaccess y tampoco. Tú has hecho algo más para que te funcione? Consigues hacer el login? Muchas gracias.

**Comment by prinick96** [comment]
@lekir prueba añadiendo lo que comenta marc2684 pero en el .htaccess que está en la carpeta **./api/**

Saludos, perdón por la demora.

**Comment by marcgdl** [comment]
Hola

Solo falta que modifiques la linea
`RewriteBase /` por `RewriteBase /api`

Esto como es obvio, para que tome como base el directorio de la api, saludos.

**Comment by lekir** [comment]
Ya me funciona!!! Muchísimas gracias!!!!
