### ISSUE TITLE
Multilenguaje en la URL

### ISSUE THREAD

**Issue by danielcanete** [prinick96/Ocrend-Framework#31]
Por ejemplo:
miweb.com/<b>empresa</b>/perfil
miweb.com/<b>company</b>/profile
El método creo que se como manejarlo pero el controlador no se como podría cambiarlo, yo programo en ingles (ej. companyController) pero para el SEO y la mejor experiencia para el usuario, en la URL debería salir en español.
Gracias de antemano.

**Comment by marcgdl** [comment]
No he analizado mucho lo que necesitas, pero se me ocurre que podría ser algo con constantes o variables, que se establezcan conforme la selección de idioma...

Habría que analizarlo, comenta si realizaste alguna solución, me interesa.
