### ISSUE TITLE
Cannot assign an empty string to a string offset in ... core/kernel/Router.php on line 43

### ISSUE THREAD

**Issue by carlosmq** [prinick96/Ocrend-Framework#33]
Buen día Prinick, 
Estoy probando el framework en un servidor para producción y me aparece este Warning
Seguí las instrucciones de la documentación para la configuración de core/config.php, según yo lo hice bien, pero, por ejemplo, al ver el código fuente, en la línea 12 de home (<link rel="stylesheet" href="views/app/css/framework.css">), pulso la liga del css y me recarga el mimo home. Cuando hago lo mismo en localhost, la misma liga me lleva al archivo css en cuestión.

Este es el Warning que queda registrado en el error_log:
PHP Warning:  Cannot assign an empty string to a string offset in /home3/carlosac/public_html/mexicoquerido.mx/core/kernel/Router.php on line 43

**Comment by prinick96** [comment]
Verifica la existencia del fichero .htaccess y de la extensión mod_rewrite de PHP

**Comment by carlosmq** [comment]
Eso era, el .htaccess. Existía, el que estaba por default en el servidor y lo modifiqué y funciona correctamente.
Gracias y por cierto. Te felicito por los videos que produces, me han enseñado mucho.
Saludos, 
Carlos
