### ISSUE TITLE
Versión 2 problema al cargar helper

### ISSUE THREAD

**Issue by AcebedoParajon** [prinick96/Ocrend-Framework#34]
Cargo el helper en el controlador de la siguiente forma:
Helper::load('strings',$this->template);

Pero me da el siguiente error:
Attempted to load class "Helper" from namespace "app\controllers".
Did you forget a "use" statement for another namespace?

Aún añadiendo en el controlador:
use Ocrend\Kernel\Helpers;

me sigue dando el mismo error

**Comment by prinick96** [comment]
En la documentación oficial se explica claramente como cargar un helper.

[Cómo cargar un helper](http://framework.ocrend.com/helpers)

En ningún punto se indica que hay que usar Helper::load()

Saludos

**Comment by AcebedoParajon** [comment]
Ok. Había visto el video en youtube:
https://youtu.be/eZPujdCgndI?list=PLDQZoQpLCoUBVbDUxr8cxVX0ik8uh5WBh
