### ISSUE TITLE
Consulta

### ISSUE THREAD

**Issue by virla01** [prinick96/Ocrend-Framework#36]
Estoy haciendo una aplicación muy simple para un cliente, y mando un dato que es un numero de orden de trabajo por medio de un formulario y lo envió como post, esta bien o tengo que hacerlo por ajax, porque me sale error, y si lo pongo en la barra de direcciones /editar/numeroDeOrden me muestra los datos bien.

**Comment by prinick96** [comment]
Canaliza tu consulta a través de [http:/foro.ocrend.com](http://foro.ocrend.com)

Dejemos los Issues para reportar problemas, etc.

Saludos
