### ISSUE TITLE
SQL SERVER

### ISSUE THREAD

**Issue by danielcanete** [prinick96/Ocrend-Framework#37]
Quería ponerte esta pregunta en tu foro, pero me decía que no tenía permisos (aunque estoy registrado).
Dentro de los motores de busqueda que soporta el framework ocrend 2, soporta SQL SERVER?
Gracias por tu tiempo.

**Comment by danielcanete** [comment]
Me auto-contesto es SQL SERVER es MS SQL y su string es mssql

**Comment by marcgdl** [comment]
Aunque no se muestra en la documentación oficial, en el archivo README en la carpeta del proyecto se muestra estas opciones
