### ISSUE TITLE
Como subir y descargar un archivo en un campo BLOB en BD MySQL...?

### ISSUE THREAD

**Issue by Scorpio-Edu** [prinick96/Ocrend-Framework#39]

**Comment by Scorpio-Edu** [comment]
Por que cerraste la pregunta...?

**Comment by prinick96** [comment]
No es relevante al código del framework

**Comment by Scorpio-Edu** [comment]
Quería saber como sería el procedimiento através del modelo de Ocrend para tratar los archivos BLOB con HTTPFoundation... Pero muchas gracias de igual manera.

**Comment by prinick96** [comment]
En ese caso, debiste completar la pregunta.
La forma sería:

```php
$blob = fopen('RUTA del binario', 'rb');
$stmt = $this->db->prepare("INSERT INTO tabla (campo) VALUES(:data)");
$stmt->bindParam(':data', $blob, \PDO::PARAM_LOB);
$stmt->execute();
```

No se en que punto necesitas HTTPFoundation, quizá si lo mandas desde un formulario pero en ese caso el procedimiento es el mismo que con cualquier archivo, una vez guardado en el servidor aplicas el código que he mostrado

**Comment by Scorpio-Edu** [comment]
justamente quería saber si necesitaba un tratado especial del archivo con HTTPFoundation ya que el Ocrend solicita trabajar preferiblemente con el HTTPFoundation. disculpa por no completar la pregunta... nuevamente muchas gracias por la ayuda.

**Comment by Scorpio-Edu** [comment]
si no estoy utilizando una conexion con PDO la función bindParam igual la toma....?

**Comment by prinick96** [comment]
En ese caso, documentate acá
http://php.net/manual/en/mysqli-stmt.send-long-data.php

**Comment by Scorpio-Edu** [comment]
excelente
