### ISSUE TITLE
Array en consulta SQL

### ISSUE THREAD

**Issue by marcgdl** [prinick96/Ocrend-Framework#4]
Hola

Estaba trabajando con el framework y de pronto las consultas de MySQL me retorna el array pero duplicado, ejemplo de un select;

`cantidad] => 2.00 
[7] => 2.00 
[precio_compra] => 100.00 
[8] => 100.00 
[iva] => 0.00 [9] => 0.00`

En el caso de un insert en el mismo modelo lo realiza duplicado, he tratado de identificar el problema, pero no veo que puedo tener de manera incorrecta.

Alguna idea de donde puede residir el problema ?, gracias.

**Comment by prinick96** [comment]
El método "select" retorna un array asociativo y secuencial, así es php. Es la razón de que puedas llegar a 'cantidad' a través del índice 0.

Si quieres un arreglo estrictamente asociativo, debes usar el método query y el método fetch_array de la propiedad **db**

``` php
$arreglo = $this->db->fetch_array($this->db->query("SQL QUERY"));
```

**Comment by marcgdl** [comment]
No veo mayor inconveniente en utilizarlo de esa manera, sin embargo la consulta de insert se duplica, utilizando la api integrada, alguna idea de como identificar el problema ?

**Comment by prinick96** [comment]
Si se duplica, es por una mala lógica, quizá estás llamando el método dos veces o algo similar, porque le insert por si solo, sólamente se ejecuta una vez.
