### ISSUE TITLE
Funcionamiento API en IIS

### ISSUE THREAD

**Issue by marcgdl** [prinick96/Ocrend-Framework#5]
Saludos

Estoy tratando de pasar la aplicación a un pequeño servidor con IIS, anteriormente lo tenía instalado en XAMPP, y funcionaba correctamente.

Al momento de pasarlo el error se genera al tratar de realizar las consultas a la api, la parque que no funciona con la api trabaja de manera correcta, alguna idea de que este ocasionando el problema ?

**Comment by marcgdl** [comment]
He recordado que utilizamos mod rewriter, he importado la regla, sin embargo ahora al realizar la consulta por la API me retorna en su totalidad la página de inicio de la aplicación. ( Es decir el index.php inicial)

**Comment by marcgdl** [comment]
Alguna idea que puede estar sucediendo ?

**Comment by prinick96** [comment]
Quizá aquí puedas conseguir información para pasar el htaccess [.htaccess en IIS](https://www.iis.net/learn/application-frameworks/install-and-configure-php-applications-on-iis/translate-htaccess-content-to-iis-webconfig)
