### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by virla01** [prinick96/Ocrend-Framework#6]
Hola Prinick no se porque (seguramente algo que hago hace q salga ese error), se produce en el inicio de sesión, lo raro es que lo dejo un ratito y presiono F5 para actualizar y me carga la pagina de inicio con todos mis datos, 

success	@	login.js:19
f	@	jquery.js:2
fireWith	@	jquery.js:2
r	@	jquery.js:3
(anonymous function)	@	jquery.js:3

Alguna idea? de que puede ser, gracias!

**Comment by marcgdl** [comment]
Hola virla01, como tip, te puedo decir que pongas el código de "login.js", es ahí donde esta generando tu error, lo que comentas que al recargar con F5 es por que se genera la sesión en PHP, pero no se termina de ejecutar correctamente tu JS.

**Comment by virla01** [comment]
el codigo de login.js es el mismo que trae por defecto, no lo he tocado, es mas varias veces (por las dudas) lo reemplace por el archivo original que tengo dentro del zip que viene el framework

**Comment by marcgdl** [comment]
Debes verificar lo que esta obteniendo el login.js cuando realizas el login.

Ya que al parecer cuando realizas la consulta AJAX, obtienes una respuesta positiva, pero al parecer lo que le estas obteniendo no es lo que esta previsto en tu código.

Usa el depurador para ver que es lo que estas obteniendo en tu consulta de login.js, ahí estará tu error.

**Comment by virla01** [comment]
ahora tambien me sale error en el depurador
jdev.js:3 
VM15763:1 Uncaught SyntaxError: Unexpected end of JSON input
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.success (http://localhost/diariosur/admin/templates/ax-admin/js/login.js:17:24)
    at f (http://localhost/diariosur/admin/templates/ax-admin/js/jdev.js:2:1219)
    at Object.fireWith [as resolveWith] (http://localhost/diariosur/admin/templates/ax-admin/js/jdev.js:2:2027)
    at r (http://localhost/diariosur/admin/templates/ax-admin/js/jdev.js:3:6263)
    at XMLHttpRequest.<anonymous> (http://localhost/diariosur/admin/templates/ax-admin/js/jdev.js:3:11523)

**Comment by marcgdl** [comment]
Lo que yo te mencionaba es que revisaras lo que te retornaba la consulta AJAX, ahí se muestra perfectamente que tiene que ver con el JSON que posiblemente estas retornando.

Haz modificado el login que viene por defecto ? tanto en el frontend como el API ?

**Comment by virla01** [comment]
No modifique nada el login ni la api

**Comment by marcgdl** [comment]
Esta complicado, tienes experiencia con PHP y JS ?, debe ser algo muy sencillo.

**Comment by virla01** [comment]
con php bastante con js maso, y si debe ser algo realmente tonto. pero gracias!

**Comment by prinick96** [comment]
Buenas, por favor, activa el DEBUG. Presiona F12 y muéstrame la consola, qué retorna exactamente.

Si te ha retornado

> VM15763:1 Uncaught SyntaxError: Unexpected end of JSON input
> at Function.parse [as parseJSON] ()
> at Object.success (http://localhost/diariosur/admin/templates/ax-admin/js/login.js:17:24)
> at f (http://localhost/diariosur/admin/templates/ax-admin/js/jdev.js:2:1219)
> at Object.fireWith [as resolveWith] (http://localhost/diariosur/admin/templates/ax-admin/js/jdev.js:2:2027)
> at r (http://localhost/diariosur/admin/templates/ax-admin/js/jdev.js:3:6263)
> at XMLHttpRequest. (http://localhost/diariosur/admin/templates/ax-admin/js/jdev.js:3:11523)

Es porque existe algún error en la respuesta, que no estás recibiendo un JSON con un formato correcto o directamente no estás recibiendo un JSON.

**Comment by virla01** [comment]
he probado de todo incluso usar el template que viene por defecto.
el error:
jdev.js:3 
VM8704:1 Uncaught SyntaxError: Unexpected end of JSON input
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.success (login.js:17)
    at f (jdev.js:2)
    at Object.fireWith [as resolveWith] (jdev.js:2)
    at r (jdev.js:3)
    at XMLHttpRequest.<anonymous> (jdev.js:3)


success @ login.js:17
f @ jdev.js:2
fireWith @ jdev.js:2
r @ jdev.js:3
(anonymous) @ jdev.js:3

es posible que en alguna otra parte del código que no sea el login y que tenga que ver con el sin querer aya cambiado algo? he visto de nuevo tus videos, los del api rest y revise todo el código ahí y esta todo correcto. Lo probé con otros navegadores y hace lo mismo
La verdad ya no se por donde mirar, y por ahí a vos podrias decirme en que archivos revisar.
Te cuento que tambien instale aplicaciones composer, imagino que no tiene nada que ver, pero por las dudas las desinstale.
Que puede ser? mi gran pregunta!

**Comment by jescobedoD** [comment]
Hola  

Tengo el mismos problema al hacer login.

`<br />
<b>Warning</b>:  Cannot assign an empty string to a string offset in <b>C:\Users\javier escobedo\Desktop\Proyectos\SSMS\Git\Fuentes\core\kernel\Router.php</b> on line <b>43</b><br />
<br />
<b>Fatal error</b>:  Uncaught RuntimeException: Unexpected data in output buffer. Maybe you have characters before an opening &lt;?php tag? in C:\Users\javier escobedo\Desktop\Proyectos\SSMS\Git\Fuentes\vendor\slim\slim\Slim\App.php:552
Stack trace:
#0 C:\Users\javier escobedo\Desktop\Proyectos\SSMS\Git\Fuentes\vendor\slim\slim\Slim\App.php(344): Slim\App-&gt;finalize(Object(Slim\Http\Response))
#1 C:\Users\javier escobedo\Desktop\Proyectos\SSMS\Git\Fuentes\vendor\slim\slim\Slim\App.php(298): Slim\App-&gt;process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#2 C:\Users\javier escobedo\Desktop\Proyectos\SSMS\Git\Fuentes\api\index.php(71): Slim\App-&gt;run()
#3 {main}
  thrown in <b>C:\Users\javier escobedo\Desktop\Proyectos\SSMS\Git\Fuentes\vendor\slim\slim\Slim\App.php</b> on line <b>552</b><br />`

este error sucede  al hacer login.

mi configuración 

*/
define('__ROOT__', '/');

//------------------------------------------------

# Constantes fundamentales
define('URL', 'http://localsite');
define('APP', 'SSMS');

alguien tiene alguna infomacion??

**Comment by prinick96** [comment]
```php
define('URL', 'http://localsite');
```

En dado caso sería
```php
define('URL', 'http://localsite/');
```

**Comment by jescobedoD** [comment]
la Url tambien la deje como 

`define('URL', 'http://localsite/');`

y sigue el error, asi que buscque en la documentacion de slim y encontre esto 

> addContentLengthHeader
When true, Slim will add a Content-Length header to the response. If you are using a runtime analytics tool, such as New Relic, then this should be disabled. 
(Default: true)
URL: https://www.slimframework.com/docs/objects/application.html

deje este parametro en false y dejo de mostrar el error.
