### ISSUE TITLE
Sobre MSSQL

### ISSUE THREAD

**Issue by marcgdl** [prinick96/Ocrend-Framework#7]
Saludos, quiero compartir que logré añadir la conexión de MSSQL de la siguiente manera;

`parent::__construct('sqlsrv:Server='.DATABASE['host'].';Database='.$DATABASE.';ConnectionPooling=0',DATABASE['user'],DATABASE['pass'],array(
            PDO::ATTR_EMULATE_PREPARES => false,
            PDO::SQLSRV_ENCODING_UTF8,
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
          ));`

Puntualizo que es necesario tener instalado el ODBC, ya que es mediante este que realiza la conexión y no directamente.

Algo mas a considerar es que se debe ajustar las consultas cambiando "LIMIT" al final de las consultas por "TOP", cuando menos es lo que me funciono correctamente.

Adicional a esto, considera como reservadas algunas palabras en las consultas como "session", que se corrigen cambiando por "[session]" por ejemplo.

Espero sea de ayuda, gracias.

**Comment by prinick96** [comment]
Se agradece el aporte, he subido el [commit](https://github.com/prinick96/Ocrend-Framework/commit/f62f43c2d8422e9a1510e2985605a8e6d617ac36)

Saludos!
