### ISSUE TITLE
Como subo una imagen usando el api rest

### ISSUE THREAD

**Issue by virla01** [prinick96/Ocrend-Framework#8]
estoy usando el ejemplo de crear un nuevo usuario con api rest, pero me sale error ya que el formulario no encripta (bueno eso es lo que creo), me guarda los datos, pero no termina de y sale un error por:
Undefined index: HTTP_X_FORWARDED_FOR  que es para poner el ip del usuario (a pesar del error, me guarda el dato correctamente) 
Undefined index: image y esto es en el upload.
los dos los tengo dentro del archivo de funciones, que en anterior mente en la otra forma funcionaban.

**Comment by prinick96** [comment]
Las transferencias de imagenes son independientes de la API, eso depende de la acción javascript que manda los datos a la API. 

Revisa esto:
http://stackoverflow.com/questions/29844976/how-to-upload-an-image-file-using-only-javascript-and-ajax

Y acomoda tu javascript a medida.
