### ISSUE TITLE
Agregar Template a Debug

### ISSUE THREAD

**Issue by marcgdl** [prinick96/Ocrend-Framework#9]
Saludos

He intentado agregar el template que se esta utilizando al DEBUG, con la intención de localizar rápidamente.

Pero no encuentro una manera adecuada de implementarlo, alguna sugerencia ?, saludos.

Ejemplo:
FRAMEWORK: 1.1.2
Controller:  ventasController
Template: -->TEMPLATE ACTUAL<--

**Comment by prinick96** [comment]
Prueba modificando el index.php para que, pases la instancia del controlador actual al debug, algo así:
```php
# Modo debug
!DEBUG ? new $Controller : new Debug($startime,new $Controller);
```

Luego en el constructor del Debug, ya tienes el controlador actual siempre, y si lo tienes a el puedes acceder al template que está manejando el controlador y por allí te vas.

**Comment by marcgdl** [comment]
Hola

Intente diferentes opciones, al final lo que para mi resulto más sencillo fue agregar en 
`vendor/league/plates/src/Template/Name.php`

`public function nameglobal($name){
        $array = explode("/",$name);
        if (!in_array("overall", $array)) {
            $GLOBALS['nametemplate'] = $name;
        }
    }

    public function setName($name)
    {
        $this->nameglobal($name);        

        $this->name = $name;

        $parts = explode('::', $this->name);

        if (count($parts) === 1) {
            $this->setFile($parts[0]);
        } elseif (count($parts) === 2) {
            $this->setFolder($parts[0]);
            $this->setFile($parts[1]);
        } else {
            throw new LogicException(
                'The template name "' . $this->name . '" is not valid. ' .
                'Do not use the folder namespace separator "::" more than once.'
            );
        }

        return $this;
    }`

Tuve que almacenarlo así ya que de lo contrario suponía modificar más archivos, ya que la mayoría de los atributos son protected, etc., además se debe filtrar ya que por este médoto pasa todo lo de overall y en teoría lo último que almacena si no se filtra es el footer.

**Comment by prinick96** [comment]
Otra cosa que pudiste hacer allí, era crear una variable de sesión y ver su valor después en el DEBUG.

Saludos
